hackatonposfiap/src/web/hackatonposfiap.web/Models/ErrorViewModel.cs
namespace hackatonposfiap.web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

hackatonposfiap/src/web/hackatonposfiap.web/Controllers/GerenciadorController.cs
using hackatonposfiap.domain.Dtos;
using hackatonposfiap.domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace hackatonposfiap.web.Controllers
{
    public class GerenciadorController : Controller
    {
        private readonly IGerenciadorService _gerenciadorService;

        public GerenciadorController(IGerenciadorService gerenciadorService)
        {
            _gerenciadorService = gerenciadorService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Process()
        {
            return View();
        }

        public async Task<List<GerenciadorImagemDto>> Gereciador()
        {
            return await _gerenciadorService.GetAll() ;
        }



    }
}

hackatonposfiap/src/web/hackatonposfiap.web/Controllers/HomeController.cs
using hackatonposfiap.web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace hackatonposfiap.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

hackatonposfiap/src/web/hackatonposfiap.web/Views/Gerenciador/Gerenciador.cshtml
@model IEnumerable<hackatonposfiap.domain.Dtos.GerenciadorImagemDto>

<h2>Listar Videos e Imagens</h2>

@* <head>
    <style type="text/css">
        #container {
            margin-top: 45px !important;
        }
    </style>

</head> *@

<div class="container">
    <table class="table" class="grid-container">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ArquivoZip)
                </th>
                <th>Detalhes</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArquivoZip)
                    </td>
                    <td>
                        @Html.ActionLink("Detalhes", "Details", new {  id = item.Id  })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

hackatonposfiap/src/web/hackatonposfiap.web/Views/Gerenciador/Index.cshtml
@model hackatonposfiap.domain.Dtos.GerenciadorVideoItemDto

@{
    ViewData["Title"] = "Index";
}

<h4>Gerenciamento de vídeos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Intervalo" class="control-label">Intervalo de tempo (seg)</label>
                <input asp-for="Intervalo" class="form-control" />
                <span asp-validation-for="Intervalo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Arquivo" class="control-label"></label>
                <input asp-for="Arquivo" type="file" class="form-control" />
                <span asp-validation-for="Arquivo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

hackatonposfiap/src/web/hackatonposfiap.web/Views/Gerenciador/ListarVideos.cshtml
@model IEnumerable<hackatonposfiap.domain.Dtos.GerenciadorImagemDto>

<h2>Listar Videos e Imagens</h2>

@* <head>
    <style type="text/css">
        #container {
            margin-top: 45px !important;
        }
    </style>

</head> *@

<div class="container">
    <table class="table" class="grid-container">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ArquivoZip)
                </th>
                <th>Detalhes</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArquivoZip)
                    </td>
                    <td>
                        @Html.ActionLink("Detalhes", "Details", new {  id = item.Id  })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

hackatonposfiap/src/web/hackatonposfiap.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hackaton - Grupo 16</h1>
    <p>Gerenciador de vídeos</p>
</div>

hackatonposfiap/src/web/hackatonposfiap.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - hackatonposfiap.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/hackatonposfiap.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">hackatonposfiap.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gerenciador" asp-action="Index">Gerenciador Videos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - hackatonposfiap.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>